### ISSUE TITLE
KNL-Flink Issue

### ISSUE THREAD

**Issue by vibhatha** [vibhatha/Flink#1]
java.lang.RuntimeException: Unable to do further retries starting the actor system
	at org.apache.flink.runtime.jobmanager.JobManager$.retryOnBindException(JobManager.scala:2147)
	at org.apache.flink.runtime.jobmanager.JobManager$.runJobManager(JobManager.scala:2087)
	at org.apache.flink.runtime.jobmanager.JobManager$$anon$9.call(JobManager.scala:1982)
	at org.apache.flink.runtime.jobmanager.JobManager$$anon$9.call(JobManager.scala:1980)
	at org.apache.flink.runtime.security.HadoopSecurityContext$1.run(HadoopSecurityContext.java:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:40)
	at org.apache.flink.runtime.jobmanager.JobManager$.main(JobManager.scala:1980)
	at org.apache.flink.runtime.jobmanager.JobManager.main(JobManager.scala)
java.lang.RuntimeException: Unable to do further retries starting the actor system
	at org.apache.flink.runtime.jobmanager.JobManager$.retryOnBindException(JobManager.scala:2147)
	at org.apache.flink.runtime.jobmanager.JobManager$.runJobManager(JobManager.scala:2087)
	at org.apache.flink.runtime.jobmanager.JobManager$$anon$9.call(JobManager.scala:1982)
	at org.apache.flink.runtime.jobmanager.JobManager$$anon$9.call(JobManager.scala:1980)
	at org.apache.flink.runtime.security.HadoopSecurityContext$1.run(HadoopSecurityContext.java:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:40)
	at org.apache.flink.runtime.jobmanager.JobManager$.main(JobManager.scala:1980)
	at org.apache.flink.runtime.jobmanager.JobManager.main(JobManager.scala)

**Comment by vibhatha** [comment]
Resolved. (Use flink run)
